### ISSUE TITLE
Text under images on http://www.scarebnb.rocks/#/listings/San Francisco, CA?_k=7ctmeb are not readable

### ISSUE THREAD

**Issue by cherishedtoken** [Devtron718/ScareBnB#1]
Noticed this in Mac Chrome 47. The text under the results is not readable. There is a white bar over the text. If I toggle off the overflow property on the element, the white bar disappears and I can read the text again.

Screenshot below:
![screen shot 2015-12-04 at 8 13 48 pm](https://cloud.githubusercontent.com/assets/7622033/11605966/f7373c36-9ac3-11e5-99ef-8402204fd6cd.png)

**Comment by Devtron3737** [comment]
Thanks!
